apiVersion: v1
kind: Service
metadata:
  name: spark-single-node
spec:
  selector:
    app: spark
  ports:
  - port: 7077  # Spark Master Port
    targetPort: 7077
    name: spark-master
  - port: 8080  # Spark UI Port
    targetPort: 8080
    name: spark-ui
  - port: 8081  # Spark Worker UI Port
    targetPort: 8081
    name: spark-worker-ui