apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: bitnami/spark:latest
        command: ["/opt/bitnami/scripts/spark/entrypoint.sh", "/run.sh"]
        args: ["spark-class", "org.apache.spark.deploy.master.Master"]
        ports:
        - containerPort: 7077  # Spark master port
        - containerPort: 8080  # Web UI port
        env:
        - name: SPARK_MODE
          value: "master"